---
apiVersion: v1
kind: Pod
metadata:
  name: my-third-pod
spec:
  containers:
    - name: nginx-container
      image: nginx:1.21.1
      livenessProbe:
        httpGet:
          path: /
          port: 80
      resources:
        requests:
          cpu: "500m"
          memory: "128Mi"
        limits:
          cpu: "1000m"
          memory: "512Mi"
      ports:
        - containerPort: 80
          protocol: TCP
